project:
  type: website
  output-dir: docs

website:
  title: "Alper Çevirgel"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: Publications.qmd
        text: Publications

format:
  html:
    theme: sandstone 
    css: styles.css
    toc: true

editor: visual   
